# Generated by Django 5.2.17 on 2026-09-30 01:43

import django.contrib.postgres.fields.ranges
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.contrib.postgres.operations import BtreeGistExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Needed by the signup_no_overlap exclusion constraint (volunteer =, period &&).
        BtreeGistExtension(),
        migrations.CreateModel(
            name='ShiftPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('weekday', models.PositiveSmallIntegerField(help_text='0 = Monday … 6 = Sunday.')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('capacity', models.PositiveSmallIntegerField(default=1)),
                ('kind', models.CharField(choices=[('regular', 'Regular shift'), ('training', 'Training session')], default='regular', max_length=10)),
                ('every_n_weeks', models.PositiveSmallIntegerField(default=1)),
                ('anchor_date', models.DateField(help_text='A date in a week this pattern runs, for every-other-week.')),
                ('active_from', models.DateField()),
                ('active_until', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['weekday', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('confirmed', 'Signed up'), ('cancelled', 'Cancelled')], default='confirmed', max_length=10)),
                ('period', django.contrib.postgres.fields.ranges.DateTimeRangeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.CharField(blank=True, max_length=200)),
                ('is_late_cancel', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['shift__starts_at'],
            },
        ),
        migrations.CreateModel(
            name='TemplateWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('promoted', 'Moved onto the shift'), ('left', 'Left the waitlist'), ('removed', 'Removed by staff'), ('expired', 'Shift passed')], default='waiting', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'waitlist entries',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlackoutPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('source', models.CharField(choices=[('federal', 'US federal holiday'), ('shelter', 'Shelter holiday')], max_length=10)),
                ('hidden', models.BooleanField(default=False, help_text="Hidden holidays aren't flagged.")),
            ],
            options={
                'ordering': ['date'],
                'constraints': [models.UniqueConstraint(fields=('date', 'name'), name='holiday_unique_per_day')],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('kind', models.CharField(choices=[('regular', 'Regular shift'), ('training', 'Training session')], default='regular', max_length=10)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('local_date', models.DateField(editable=False, help_text='The shelter-time date it starts on.')),
                ('capacity', models.PositiveSmallIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('cancelled', 'Cancelled')], default='scheduled', max_length=10)),
                ('cancel_reason', models.CharField(blank=True, max_length=200)),
                ('holiday_name', models.CharField(blank=True, max_length=100)),
                ('edited_by_hand', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['starts_at', 'title'],
            },
        ),
    ]
