# Generated by Django 5.2.17 on 2026-09-30 01:43

import django.contrib.postgres.constraints
import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduling', '0001_initial'),
        ('training', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='required_training',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='training.trainingtype'),
        ),
        migrations.AddField(
            model_name='shift',
            name='teaches',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='training.trainingtype'),
        ),
        migrations.AddField(
            model_name='shiftpattern',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shiftpattern',
            name='required_training',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='training.trainingtype'),
        ),
        migrations.AddField(
            model_name='shiftpattern',
            name='teaches',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='training.trainingtype'),
        ),
        migrations.AddField(
            model_name='shift',
            name='pattern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts', to='scheduling.shiftpattern'),
        ),
        migrations.AddField(
            model_name='signup',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='signup',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='signup',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signups', to='scheduling.shift'),
        ),
        migrations.AddField(
            model_name='signup',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='templateweek',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='scheduling_template_name_ci_unique'),
        ),
        migrations.AddField(
            model_name='shiftpattern',
            name='template_week',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patterns', to='scheduling.templateweek'),
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waitlist', to='scheduling.shift'),
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waitlist_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='blackoutperiod',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='blackout_range_valid'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['local_date', 'status'], name='scheduling__local_d_20eeab_idx'),
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='shift_ends_after_start'),
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.CheckConstraint(condition=models.Q(('capacity__gte', 1)), name='shift_capacity_min'),
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'training'), ('teaches__isnull', False)), models.Q(('kind', 'regular'), ('teaches__isnull', True)), _connector='OR'), name='shift_kind_teaches'),
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.UniqueConstraint(condition=models.Q(('pattern__isnull', False)), fields=('pattern', 'local_date'), name='shift_one_per_pattern_per_day'),
        ),
        migrations.AddConstraint(
            model_name='signup',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'confirmed')), fields=('shift', 'volunteer'), name='signup_once_per_shift'),
        ),
        migrations.AddConstraint(
            model_name='signup',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status', 'confirmed')), expressions=[('volunteer', '='), ('period', '&&')], name='signup_no_overlap'),
        ),
        migrations.AddConstraint(
            model_name='shiftpattern',
            constraint=models.CheckConstraint(condition=models.Q(('weekday__gte', 0), ('weekday__lte', 6)), name='pattern_weekday_valid'),
        ),
        migrations.AddConstraint(
            model_name='shiftpattern',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='pattern_ends_after_start'),
        ),
        migrations.AddConstraint(
            model_name='shiftpattern',
            constraint=models.CheckConstraint(condition=models.Q(('capacity__gte', 1)), name='pattern_capacity_min'),
        ),
        migrations.AddConstraint(
            model_name='shiftpattern',
            constraint=models.CheckConstraint(condition=models.Q(('every_n_weeks__in', [1, 2])), name='pattern_every_1_or_2_weeks'),
        ),
        migrations.AddConstraint(
            model_name='shiftpattern',
            constraint=models.CheckConstraint(condition=models.Q(('active_until__isnull', True), ('active_until__gte', models.F('active_from')), _connector='OR'), name='pattern_active_range_valid'),
        ),
        migrations.AddConstraint(
            model_name='shiftpattern',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'training'), ('teaches__isnull', False)), models.Q(('kind', 'regular'), ('teaches__isnull', True)), _connector='OR'), name='pattern_kind_teaches'),
        ),
        migrations.AddConstraint(
            model_name='waitlistentry',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'waiting')), fields=('shift', 'volunteer'), name='waitlist_once_per_shift'),
        ),
    ]
