# Generated by Django 5.2.17 on 2026-09-30 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='conflict_reported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
