# Generated by Django 5.2.17 on 2026-09-30 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_signup_conflict_reported'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='was_urgent',
            field=models.BooleanField(default=False),
        ),
    ]
