# Generated by Django 5.2.17 on 2026-09-30 19:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_signup_was_urgent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='needs_approval',
            field=models.BooleanField(default=False, help_text='Staff approve each sign-up (for example, large events).'),
        ),
        migrations.AddField(
            model_name='shiftpattern',
            name='needs_approval',
            field=models.BooleanField(default=False, help_text='Staff approve each sign-up (for example, large events).'),
        ),
        migrations.CreateModel(
            name='SignupRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('waiting', 'Waiting for approval'), ('approved', 'Approved'), ('declined', 'Not approved'), ('withdrawn', 'Taken back'), ('closed', 'Closed: the shift passed or was cancelled')], default='waiting', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='scheduling.shift')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signup_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'waiting')), fields=('shift', 'volunteer'), name='request_once_per_shift')],
            },
        ),
    ]
