# Generated by Django 5.2.17 on 2026-09-30 01:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShelterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelter_name', models.CharField(max_length=200)),
                ('shelter_phone', models.CharField(blank=True, max_length=30)),
                ('shelter_email', models.EmailField(blank=True, max_length=254)),
                ('self_cancel_hours', models.PositiveSmallIntegerField(default=24, help_text='Volunteers can cancel on their own until this many hours before.')),
                ('urgent_threshold_hours', models.PositiveSmallIntegerField(choices=[(24, '24 hours'), (48, '48 hours')], default=24, help_text='A cancellation this close to the shift is urgent.')),
                ('notify_emails', models.TextField(blank=True, help_text='Staff who get notification emails, one address per line.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'shelter settings',
                'verbose_name_plural': 'shelter settings',
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='core_settings_single_row')],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=60)),
                ('target_repr', models.CharField(blank=True, max_length=200)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, help_text='Who made the change; empty when the app did it automatically.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['target_user', 'created_at'], name='core_audite_target__a51b64_idx')],
            },
        ),
    ]
