# Generated by Django 5.2.17 on 2026-09-30 17:41

from django.db import migrations, models


def use_72_hours(apps, schema_editor):
    """The shelter asked for 72 hours' notice during testing; log the change like any other."""
    ShelterSettings = apps.get_model("core", "ShelterSettings")
    AuditEvent = apps.get_model("core", "AuditEvent")
    for row in ShelterSettings.objects.exclude(urgent_threshold_hours=72):
        old = row.urgent_threshold_hours
        row.urgent_threshold_hours = 72
        row.save(update_fields=["urgent_threshold_hours"])
        AuditEvent.objects.create(
            action="settings.changed",
            details={
                "changes": {"urgent_threshold_hours": {"from": old, "to": 72}},
                "why": "The shelter asked for 72 hours' notice during testing.",
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheltersettings',
            name='urgent_threshold_hours',
            field=models.PositiveSmallIntegerField(choices=[(24, '24 hours'), (48, '48 hours'), (72, '72 hours')], default=72, help_text='A cancellation this close to the shift is urgent.'),
        ),
        migrations.RunPython(use_72_hours, migrations.RunPython.noop),
    ]
