# Generated by Django 5.2.17 on 2026-10-01 00:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(default=django.utils.timezone.now)),
                ('role', models.CharField(blank=True, help_text='Blank when signed out.', max_length=20)),
                ('route', models.CharField(help_text='The page\'s name, like "shifts:shift".', max_length=100)),
                ('method', models.CharField(max_length=8)),
                ('status', models.PositiveSmallIntegerField()),
                ('duration_ms', models.PositiveIntegerField()),
                ('device', models.CharField(max_length=10)),
                ('came_from', models.CharField(blank=True, help_text="The previous page's name.", max_length=100)),
                ('form_problem', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-at'],
                'indexes': [models.Index(fields=['at'], name='insights_pa_at_5fdb58_idx'), models.Index(fields=['route', 'at'], name='insights_pa_route_015e58_idx'), models.Index(fields=['user', 'at'], name='insights_pa_user_id_3ee994_idx')],
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(default=django.utils.timezone.now)),
                ('code', models.CharField(max_length=10)),
                ('status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ref', models.CharField(blank=True, max_length=10)),
                ('route', models.CharField(blank=True, max_length=100)),
                ('path', models.CharField(blank=True, max_length=200)),
                ('method', models.CharField(blank=True, max_length=8)),
                ('role', models.CharField(blank=True, max_length=20)),
                ('summary', models.CharField(blank=True, max_length=300)),
                ('details', models.TextField(blank=True)),
                ('emailed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-at'],
                'indexes': [models.Index(fields=['code', 'route', 'at'], name='insights_pr_code_8289c0_idx'), models.Index(fields=['at'], name='insights_pr_at_6aceaa_idx')],
            },
        ),
    ]
