# Generated by Django 5.2.17 on 2026-09-30 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_starting_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerprofile',
            name='wants_reminders',
            field=models.BooleanField(default=True, help_text='Email reminders before their shifts (they can turn these off).'),
        ),
    ]
