# Generated by Django 5.2.17 on 2026-09-30 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_volunteerprofile_wants_reminders'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerprofile',
            name='is_minor',
            field=models.BooleanField(default=False, help_text="Under 18. Staff see it; it doesn't change what they can take."),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='needs_approval',
            field=models.BooleanField(default=False, help_text='Staff approve each shift they ask for. They can still sign in.'),
        ),
    ]
