# Generated by Django 5.2.17 on 2026-09-30 17:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('weekly', 'Sunday digest'), ('monthly', 'Monthly summary')], max_length=10)),
                ('period_start', models.DateField(help_text='The Monday of the week, or the 1st of the month.')),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('recipients', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['-sent_at'],
                'constraints': [models.UniqueConstraint(fields=('kind', 'period_start'), name='report_once_per_period')],
            },
        ),
    ]
