# Generated by Django 5.2.17 on 2026-09-30 17:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SentReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('evening', 'Evening-before reminder'), ('week', "Sunday list of the week's shifts"), ('birthday', 'Birthday email')], max_length=10)),
                ('for_date', models.DateField(help_text='The shift day, the Monday of the week, or the birthday.')),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_at'],
                'constraints': [models.UniqueConstraint(fields=('kind', 'user', 'for_date'), name='reminder_once_per_person_per_date')],
            },
        ),
    ]
